name: CI

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
          - linux-musl
          - windows
          - macos
          - macos-arm-64
          - linux-arm-64
          - linux-arm-32
        include:
          - build: linux-musl
            os: ubuntu-latest
            toolchain: stable
            target: x86_64-unknown-linux-musl

          - build: windows
            os: windows-latest
            toolchain: stable
            target: x86_64-pc-windows-msvc

          - build: macos
            os: macos-latest
            toolchain: stable
            target: x86_64-apple-darwin

          - build: macos-arm-64
            os: macos-11
            toolchain: nightly
            target: aarch64-apple-darwin
            cross: true

          - build: linux-arm-64
            os: ubuntu-latest
            toolchain: nightly
            target: aarch64-unknown-linux-musl
            cross: true

          - build: linux-arm-32
            os: ubuntu-latest
            toolchain: nightly
            target: arm-unknown-linux-musleabihf
            cross: true

    steps:
      - name: install musl-tools if musl target
        if: ${{ contains(matrix.target, 'musl') }}
        run: sudo apt install musl-tools

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ matrix.target }}-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ matrix.target }}-build-
            ${{ matrix.target }}-

      - name: Install cross compiler
        if: ${{ matrix.cross }}
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cross

      - name: Use cross instead of cargo for cross compilation
        if: ${{ matrix.cross }}
        run: cross build --release --target ${{ matrix.target }}

      - uses: actions-rs/cargo@v1
        if: ${{ !matrix.cross }}
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Compress compiled binary
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          cd target/${{ matrix.target }}/release
          tar czf elm-solve-deps_${{ matrix.target }}.tar.gz elm-solve-deps

      - uses: actions/upload-artifact@v2
        if: ${{ !startsWith(matrix.os, 'windows') }}
        with:
          name: elm-solve-deps_${{ matrix.target }}.tar.gz
          path: target/${{ matrix.target }}/release/elm-solve-deps_${{ matrix.target }}.tar.gz

      - uses: actions/upload-artifact@v2
        if: ${{ startsWith(matrix.os, 'windows') }}
        with:
          name: elm-solve-deps_${{ matrix.target }}
          path: target/${{ matrix.target }}/release/elm-solve-deps.exe

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: test-${{ matrix.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            test-${{ matrix.os }}-

      - uses: actions-rs/cargo@v1
        with:
          command: test

  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Check clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -D warnings
        with:
          command: clippy

  check_documentation:
    name: Check the documentation build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Download cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/
            target/
          key: doc-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            doc-${{ matrix.os }}-

      - name: Check documentation
        working-directory: ./elm-solve-deps-lib
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps
